#!/usr/bin/env bash
# Sync assets/ between repo and onedrive:/Shared/HumanRobot/assets/.
#
# Usage:
#   scripts/sync_assets.sh pull [SUBDIR]   # remote -> local (non-destructive)
#   scripts/sync_assets.sh push [SUBDIR]   # local  -> remote (non-destructive)
#   scripts/sync_assets.sh diff [SUBDIR]   # read-only check (hash compare)
#
# SUBDIR is optional; without it we operate on the whole assets/ tree.
# Common choices: exr, embodiments, manual_grasps, avatars, objects.
#
# Notes:
#   - Local `assets/avatars` and `assets/objects` are SYMLINKS to external dirs.
#     With `--copy-links`, writes land in the symlink targets; drop the flag
#     to skip symlinked subtrees entirely. This script defaults to --copy-links
#     so the actual asset files are the ones compared/transferred.
#   - "pull" and "push" use `rclone copy` (additive). For true destructive
#     sync (removes extras on the destination) use `rclone sync` by hand.
#   - $REMOTE/objects.zip is a separate, manually-maintained artifact (see
#     fetch_objects_zip.sh) for people using OneDrive's browser download
#     instead of rclone -- it is NOT touched by push/pull and must be
#     regenerated by hand after a `push objects` that changes objects/:
#       cd assets && zip -r -q /tmp/objects.zip objects && \
#       rclone copyto /tmp/objects.zip onedrive:/Shared/HumanRobot/assets/objects.zip

set -euo pipefail

REMOTE=onedrive:/Shared/HumanRobot/assets
REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
LOCAL="$REPO_ROOT/assets"

mode="${1:-}"
subdir="${2:-}"

if [[ -z "$mode" ]]; then
    echo "Usage: $0 {pull|push|diff} [SUBDIR]" >&2
    exit 2
fi

src_remote="$REMOTE/"
dst_remote="$REMOTE/"
src_local="$LOCAL/"
dst_local="$LOCAL/"
if [[ -n "$subdir" ]]; then
    sub="${subdir%/}/"
    src_remote="$REMOTE/$sub"
    dst_remote="$REMOTE/$sub"
    src_local="$LOCAL/$sub"
    dst_local="$LOCAL/$sub"
fi

common_flags=(--copy-links --transfers 8 --checkers 16 --stats 10s --stats-one-line)

case "$mode" in
    pull)
        echo "=== PULL  $src_remote -> $dst_local ==="
        mkdir -p "$dst_local"
        rclone copy "$src_remote" "$dst_local" "${common_flags[@]}"
        ;;
    push)
        echo "=== PUSH  $src_local -> $dst_remote ==="
        rclone copy "$src_local" "$dst_remote" "${common_flags[@]}"
        ;;
    diff)
        echo "=== DIFF  $src_remote  vs  $src_local ==="
        # --one-way so we see missing-on-local first; swap args for the
        # opposite direction.
        rclone check "$src_remote" "$src_local" --one-way --copy-links || true
        ;;
    *)
        echo "Unknown mode: $mode" >&2
        exit 2
        ;;
esac
