"""Grasp pose loading and transforms.

Each object can define grasp poses in a YAML file (grasp_poses.yml) alongside
its mesh assets.  At runtime the pipeline is:

    1. Load grasp pose (local to object frame)
    2. T_world_tcp   = T_world_object  @ T_object_grasp
    3. T_world_link  = T_world_tcp     @ inv(T_tcp_offset)   # for IK
    4. Pre-grasp     = back off along TCP Z axis by pre_distance
"""

import yaml
import numpy as np
from pathlib import Path
from .utils import Pose, ASSETS_PATH


# ------------------------------------------------------------------
# Grasp pose data
# ------------------------------------------------------------------

class GraspPose:
    """One grasp definition in object-local frame.

    Two frame conventions are supported via ``scale_frame``:

    - ``"mesh_unit"`` (default): positions are in the unscaled mesh frame
      (as generated by the historical grasp preprocessing tools
      at scale=1). ``to_world``/``pre_grasp_world`` multiply by
      ``object_scale`` before transforming.
    - ``"runtime"``: positions are already in the runtime-scaled object
      frame (as produced by the historical manual grasp tooling,
      which records gripper-in-object-local with the object's model-scale
      already applied). ``object_scale`` is ignored at ``to_world`` time —
      re-scaling would shrink the grasp.

    ``source`` (``"auto"``/``"manual"``) is informational, mainly to let
    callers prefer manually-validated grasps when both kinds exist.
    """

    def __init__(
        self,
        name: str,
        position,
        quaternion,
        pre_distance: float = 0.12,
        source: str = "auto",
        scale_frame: str = "mesh_unit",
        category: str = None,
        kinematic_pin: bool = False,
    ):
        self.name = name
        self.pose = Pose(position, quaternion)
        self.pre_distance = pre_distance
        self.source = source
        self.scale_frame = scale_frame
        # Optional grouping tag (e.g. "body" vs "handle" for a knife) so
        # tasks can filter the candidate pool to just the grasps that
        # match the scenario.  None means "matches any category filter".
        self.category = category
        # When True, callers (e.g. grasp_helper_test) should re-apply the
        # spawn pose every physics step until the gripper closes, so the
        # object stays in a forced orientation that physics alone wouldn't
        # maintain (gong on edge, tall thin objects, etc.).
        self.kinematic_pin = kinematic_pin

    def _scaled_pose(self, object_scale: float) -> Pose:
        """Return grasp pose with position scaled to match the loaded mesh."""
        if self.scale_frame == "runtime" or object_scale == 1.0:
            return self.pose
        return Pose(self.pose.p * object_scale, self.pose.q)

    def to_world(self, object_pose: Pose, object_scale: float = 1.0) -> Pose:
        """Transform grasp TCP to world frame."""
        return object_pose * self._scaled_pose(object_scale)

    def pre_grasp_world(self, object_pose: Pose, object_scale: float = 1.0) -> Pose:
        """Pre-grasp TCP in world frame (back off along TCP Z)."""
        tcp_world = self.to_world(object_pose, object_scale)
        R = tcp_world.to_matrix()[:3, :3]
        tcp_z = R[:, 2]  # Z column = approach direction
        pre_pos = tcp_world.p - self.pre_distance * tcp_z
        return Pose(pre_pos, tcp_world.q)


# ------------------------------------------------------------------
# Loading
# ------------------------------------------------------------------

def load_grasp_poses(object_name: str, model_id: int = None, robot_type: str = None) -> list[GraspPose]:
    """Load grasp poses from ``assets/objects/<object_name>/``.

    When ``robot_type`` is given, entries from ``grasp_poses_<robot_type>.yml``
    are merged with the generic ``grasp_poses.yml`` (robot-specific entries
    appear first, then generic).  Entries with duplicate ``name`` are
    deduplicated (the robot-specific one wins).  This keeps hand-curated
    named grasps in the generic file (e.g. ``body_top_down``) reachable even
    after a robot-specific file is created.

    Fallback: if a non-franka ``robot_type`` was requested but no
    ``grasp_poses_<robot_type>.yml`` exists, the franka file (when
    present) is appended last as a parallel-jaw fallback so tasks that
    only ship hand-tuned franka grasps (075_bread, 002_bowl, …) still
    work for xarm7 / arx_x5 / ur5_wsg / piper / stretch. Grasps are in
    object-local frame so the same pose works for any similar-width
    parallel-jaw gripper.
    """
    obj_dir = ASSETS_PATH / "objects" / object_name
    candidate_files = []
    if robot_type:
        robot_file = obj_dir / f"grasp_poses_{robot_type}.yml"
        if robot_file.exists():
            candidate_files.append(robot_file)
    generic_file = obj_dir / "grasp_poses.yml"
    if generic_file.exists():
        candidate_files.append(generic_file)

    def _read_file(grasp_file) -> list[GraspPose]:
        with open(grasp_file, encoding="utf-8") as f:
            data = yaml.safe_load(f) or {}
        out = []
        for g in data.get("grasps", []):
            name = g["name"]
            if name in seen_names:
                continue
            if model_id is not None and "model_ids" in g:
                if model_id not in g["model_ids"]:
                    continue
            seen_names.add(name)
            out.append(GraspPose(
                name=name,
                position=g["position"],
                quaternion=g["quaternion"],
                pre_distance=g.get("pre_distance", 0.12),
                source=g.get("source", "auto"),
                scale_frame=g.get("scale_frame", "mesh_unit"),
                category=g.get("category"),
                kinematic_pin=g.get("kinematic_pin", False),
            ))
        return out

    grasps = []
    seen_names = set()
    for grasp_file in candidate_files:
        grasps.extend(_read_file(grasp_file))

    # Last-resort fallback: if a non-franka robot was requested but we
    # found no grasps in either its own file or the generic one, fall
    # back to grasp_poses_franka.yml if it exists. Grasps are in
    # object-local frame and franka's parallel-jaw gripper is similar
    # enough to xarm7 / arx_x5 / ur5_wsg / piper that the same poses are
    # usable. Only kicks in when nothing else worked, so robots with
    # their own grasps (tiago_pro) don't pick up extra franka entries.
    if not grasps and robot_type and robot_type != "franka":
        franka_file = obj_dir / "grasp_poses_franka.yml"
        if franka_file.exists() and franka_file not in candidate_files:
            grasps.extend(_read_file(franka_file))
    # Prefer manually-validated grasps: move them to the front of the list
    # while keeping the relative order within each group stable.
    grasps.sort(key=lambda g: 0 if g.source == "manual" else 1)
    return grasps


def has_manual_grasp(object_name: str, robot_type: str = "franka") -> bool:
    """True if the object has a ``source: manual`` grasp annotation."""
    yml = ASSETS_PATH / "objects" / object_name / f"grasp_poses_{robot_type}.yml"
    if not yml.exists():
        return False
    with open(yml, encoding="utf-8") as f:
        data = yaml.safe_load(f) or {}
    return any(g.get("source") == "manual" for g in data.get("grasps", []))


def read_save_object_quat(object_name: str, robot_type: str = "franka") -> np.ndarray:
    """Read ``save_object_quat`` from the manual grasp annotation, or identity."""
    yml = ASSETS_PATH / "objects" / object_name / f"grasp_poses_{robot_type}.yml"
    if not yml.exists():
        return np.array([1.0, 0.0, 0.0, 0.0])
    with open(yml, encoding="utf-8") as f:
        data = yaml.safe_load(f) or {}
    for g in data.get("grasps", []):
        if g.get("source") == "manual" and "save_object_quat" in g:
            return np.array(g["save_object_quat"], dtype=np.float64)
    return np.array([1.0, 0.0, 0.0, 0.0])


def get_grasp_pose(object_name: str, grasp_name: str = None, model_id: int = None, robot_type: str = None) -> GraspPose:
    """Get a specific grasp pose by name (or first available)."""
    grasps = load_grasp_poses(object_name, model_id, robot_type=robot_type)
    if not grasps:
        raise ValueError(f"No grasp poses found for {object_name}")
    if grasp_name:
        for g in grasps:
            if g.name == grasp_name:
                return g
        raise ValueError(f"Grasp '{grasp_name}' not found for {object_name}")
    return grasps[0]


# ------------------------------------------------------------------
# Object config (keypoints, properties)
# ------------------------------------------------------------------

def load_object_config(object_name: str) -> dict:
    """Load object config from assets/objects/<object_name>/config.yml."""
    config_file = ASSETS_PATH / "objects" / object_name / "config.yml"
    if not config_file.exists():
        return {}
    with open(config_file, encoding="utf-8") as f:
        return yaml.safe_load(f) or {}


def get_keypoint(object_name: str, keypoint_name: str) -> np.ndarray:
    """Get a keypoint position in object local frame."""
    cfg = load_object_config(object_name)
    kps = cfg.get("keypoints", {})
    if keypoint_name not in kps:
        raise ValueError(f"Keypoint '{keypoint_name}' not found for {object_name}")
    return np.asarray(kps[keypoint_name], dtype=np.float64)


# ------------------------------------------------------------------
# TCP ↔ link transforms
# ------------------------------------------------------------------

def tcp_to_link_pose(tcp_pose: Pose, tcp_offset: Pose) -> Pose:
    """Convert TCP world pose to IK link target.

    T_world_link = T_world_tcp @ inv(T_link_tcp)
    where tcp_offset = T_link_tcp (TCP in link frame).
    """
    return tcp_pose * tcp_offset.inv()


def link_to_tcp_pose(link_pose: Pose, tcp_offset: Pose) -> Pose:
    """Convert link world pose to TCP world pose.

    T_world_tcp = T_world_link @ T_link_tcp
    """
    return link_pose * tcp_offset
